### ISSUE TITLE
domain name

### ISSUE THREAD

**Issue by maxmonkey950** [dotbalo/k8s#2]
你好，我再安装openldap的时候发现一点问题，我改过environment目录下的 my-env.startup.yaml文件中的LDAP_BASE_DN：asd.org,然而并没有生效，然后我又改了image-v2/environment/default.startup.yaml文件中的bind_id: cn=admin,dc=asd,dc=org  
还是没有生效，请教一下怎么去改这个名称呢。

**Comment by dotbalo** [comment]
您好，有三种方式可以修改Domain，
1. 在deployment文件中添加对应的环境变量，详情变量可以参考这个链接：https://github.com/osixia/docker-openldap#environment-variables
Domain应该是LDAP_DOMAIN，然后还需要改一下这个变量LDAP_REPLICATION_HOSTS。

2. 可以使用image-v2目录，自己生成一个image，然后用于自定义domain。

3. 如果是直接修改environment目录，需要使用environment的file-to-base64.sh脚本，重新生成对应文件的base64编码，然后修改ldap-secret.yaml的base64为你生成的即可。
